name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Builder
      run: make run -C Creational/Builder
    - name: Factory
      run: make run -C Creational/Factory
    - name: Prototype
      run: make run -C Creational/Prototype
    - name: Singleton
      run: make run -C Creational/Singleton
    - name: Adapter
      run: make run -C Structural/Adapter
    - name: Bridge
      run: make run -C Structural/Bridge
    - name: Composite
      run: make run -C Structural/Composite
    - name: Decorator
      run: make run -C Structural/Decorator
    - name: Facade
      run: make run -C Structural/Facade
    - name: Flyweight
      run: make run -C Structural/Flyweight
    - name: Proxy
      run: make run -C Structural/Proxy
    - name: Chain Of Responsability
      run: make run -C Behavioral/ChainOfResponsability
    - name: Command
      run: make run -C Behavioral/Command
    - name: Interpreter
      run: make run -C Behavioral/Interpreter
    - name: Iterator
      run: make run -C Behavioral/Iterator
    - name: Mediator
      run: make run -C Behavioral/Mediator
    - name: Memento
      run: make run -C Behavioral/Memento
    - name: NullObject
      run: make run -C Behavioral/NullObject
    - name: Observer
      run: make run -C Behavioral/Observer
    - name: Visitor
      run: make run -C Behavioral/Visitor
